### ISSUE TITLE
[Suggest] admin scrollbar 및 constants.ts를 scss 변환 제안

### ISSUE THREAD

**Issue by kingyong9169** [CMI-OSS/cbnu-alrami#140]
## 💁‍♀️ 제안 사항
admin에서는 scrollbar 허용 및 constants.ts를 scss 변환에 대한 제안입니다.

### ✅ 참고 사항
admin은 웹사이트로 사용자에게 제공되기 때문에 overflow에 대한 scrollbar가 있는 것이 UX에 더 좋을 것 같다는 의견입니다!

현재 `shared/src/styles/global.scss`에 
``` scss
::-webkit-scrollbar {
    display: none; /* Chrome, Safari, Opera*/
}
```
로 되어 있어 admin까지 영향을 받고 있어 스크롤바가 생기지 않는 모습입니다. 따라서 위 scss코드는 mobile에서 선언하여 관리하는 것에 대한 제안입니다!

또한, constants.ts는 scss파일에서 변수로 사용이 되지 않는 모습입니다. 따라서 `variables.scss`라는 파일을 만들어 이 파일에서 css variables를 관리하는 것을 제안합니다!
